###
http://localhost:9110/jasper-report/approval-status/export/pdf?columns=status

###
http://localhost:9110/jasper-report/approval-status/export/pdf?columns=type,bankReference,status

###
http://localhost:9110/jasper-report/approval-status/export/pdf?columns=type,bankReference,account,status

###
http://localhost:9110/jasper-report/approval-status/export/pdf?columns=status,amount,account,bankReference,type

###
http://localhost:9110/jasper-report/approval-status/export/pdf



###
http://localhost:48080/report/approval-status/export/pdf

### merge
http://localhost:48080/report/approval-status/export/pdf/merged