server:
  port: 9000
  servlet:
    context-path: /auth-server

spring:
  application:
    name: creed-author-server

management:
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

creed:
  metrics:
    jvm-memory:
      initial-delay-ms: 10000
      interval-ms: 30000
