server:
  port: 8081

spring:
  application:
    name: creed-resource-catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

creed:
  oauth2:
    jwk-set-cache-minutes: 10
