server:
  port: 8080

spring:
  application:
    name: creed-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-resource
              uri: http://127.0.0.1:8081
              predicates:
                - Path=/api/catalog/**
            - id: order-resource
              uri: http://127.0.0.1:8082
              predicates:
                - Path=/api/order/**

creed:
  oauth2:
    jwk-set-cache-minutes: 10
  resource:
    catalog-url: http://127.0.0.1:8081/api/catalog/items
    order-url: http://127.0.0.1:8082/api/order/items
