creed.ssl.bundle.jks.creed-jks-server.keystore=JKS
creed.ssl.bundle.jks.creed-jks-server.keystore.location="classpath:certs/server-keystore.p12"
creed.ssl.bundle.jks.creed-jks-server.keystore.password="${creed.ssl.keystore-password}"